### ISSUE TITLE
[错误] “消息”界面还未采用本地化

### ISSUE THREAD

**Issue by doodlehuang** [Stapxs/Stapxs-QQ-Lite-2.0#10]
**描述错误**

“消息”界面部分文本仍然硬编码简体中文，无法通过本地化设置改变显示语言。
**复现流程**

**截图**

![image](https://user-images.githubusercontent.com/25525621/205666109-40f578f3-eb1a-41ca-ab97-5bfb46535449.png)

**版本信息**

**更多**

**Comment by Stapxs** [comment]
#15
