### ISSUE TITLE
[Bug] 拉格朗无法加载消息和好友分组

### ISSUE THREAD

**Issue by htxzdfunny** [Stapxs/Stapxs-QQ-Lite-2.0#100]
### 错误来源

Stapxs QQ Lite

### 描述错误

连接到 Lagrange.OneBot 后, 消息列表空白, 且未能正确加载好友分组
(图片在下面)

### 复现流程

1. 从 Releases 下载最新最热 [v2.7.13](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/releases/tag/v2.7.13)
2. 跑
3. 输入链接地址连接到 Lagrange.OneBot
4. 炸

### 截图

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/a7290163-df82-432e-ba98-1408fdf42415)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/df8fb7d1-76d3-4a52-ab9d-5edaa5d88df5)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/ef5ffa71-a61c-4ba7-96f6-b4080445d100)

### 版本信息

```
Debug Info - 6/22/2024, 2:01:55 PM
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> chrome
    Browser Version  -> 118.0.5993
    Electron Version -> 27.3.11
    Install Type     -> raw
Application Info:
    Uptime           -> 148190 ms
    Package Version  -> 2.7.13
    Runtime env      -> production
    Service Work     -> false
Backend Info:
    Bot Info Name    -> Lagrange.OneBot
    Bot Info Version -> 0.0.3
    Loaded Config    -> Lagrange.OneBot
View Info:
    Doc Width        -> 645 px
Network Info:
    Github           -> 232 ms
    Link API         -> 216 ms
```

### 更多

好消息 #98 里的问题都修好了
坏消息 来了个 #100

**Comment by Stapxs** [comment]
嘘—— 拉格兰好久之前就支持好友分组获取了但是我还没写支持（x
马上去马上去 😭

**Comment by htxzdfunny** [comment]
> 嘘—— 拉格兰好久之前就支持好友分组获取了但是我还没写支持（x 马上去马上去 😭

那个  消息列表一片空白是正常现象嘛）

**Comment by Stapxs** [comment]
消息列表你去好友/群列表里发起会话就好（x

默认只推私聊的消息进消息列表，群只推 AT 回复和 AT 全体和特别关心的消息进消息列表
特别关心在所有情况下都会以高权限通知（linux）通知

当然你也可以打开通知所有新消息的功能：

<img width="482" alt="image" src="https://github.com/user-attachments/assets/8c287b90-9bca-49c1-b6f3-939885bcb239">

由于没法获取群的通知设置，在将来的版本或许会添加自带的每个群独立的通知设置功能。

**Comment by Stapxs** [comment]
https://github.com/LagrangeDev/Lagrange.Core/pull/477

**Comment by Stapxs** [comment]
拉格兰那边的更新计划被搁置了，暂时关闭此 issue。
如果依旧有此功能需求请重新打开（

**Comment by Stapxs** [comment]
等待八月累计更新 - 1 合并：
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/pull/114

**Comment by Stapxs** [comment]
dac4a65
