### ISSUE TITLE
[建议] 表情回应可关闭

### ISSUE THREAD

**Issue by MoonLeeeaf** [Stapxs/Stapxs-QQ-Lite-2.0#101]
用习惯了旧版QQ，现在这个功能跑到了这里还真不习惯，希望可以在设置单独设置个开关（逃
![Screenshot_20240715-101937_Via](https://github.com/user-attachments/assets/c61d56d4-cc5b-4af5-8321-f6504ce5550a)
主要有些碍事（小声）

**Comment by Stapxs** [comment]
更新已提交部署，可以康康有没有什么问题然后关掉 issue（瘫

**Comment by MoonLeeeaf** [comment]
暂时没有环境能测试（我运行 NapCat 的电脑怎么炸辣（恼）），等我晚上来测试罢（逃

**Comment by Stapxs** [comment]
别急别急我写了个 bug 出来 😭

**Comment by MoonLeeeaf** [comment]
> 别急别急我写了个 bug 出来 😭

完啦真的写了个大的 bug 出来
消息发出去服务端反馈 发生错误{} -> 自动检测、CQ和Array试过了
群图片无法加载（悲

心疼作者😭
加油作者🌚🌹

**Comment by Stapxs** [comment]
这下好了（瘫

**Comment by MoonLeeeaf** [comment]
可怜的作者（悲
