### ISSUE TITLE
[错误?] 自己发的消息需要手动刷新才能显示

### ISSUE THREAD

**Issue by MoonLeeeaf** [Stapxs/Stapxs-QQ-Lite-2.0#103]
### 错误来源

其他

### 描述错误

关于错误来源..我并不清楚是因为 QQ Bot 不接自己消息还是网页客户端没能正确处理消息，因此暂时没有填（逃

如题，在此客户端发送任意消息到任意群聊/私聊，都不会主动接收（？），需要手动退出再进入才能获取到

### 复现流程

1. 选择任意联系人/群聊
2. 自己发送消息
3. 然后你就会发现你的消息不见辣（雾
4. 再次点击当前聊天对象
5. 然后你的消息回来辣（喜

### 截图

没截图呢...
视频因为大小问题无法上传（大悲

### 版本信息

```
Debug Info - 2024/7/15 10:47:13
================================
System Info:
    OS Name          -> Android OS
    Browser Name     -> chrome
    Browser Version  -> 90.0.4430
Application Info:
    Uptime           -> 11622 ms
    Package Version  -> 2.7.13
    Runtime env      -> production
    Service Work     -> true
Backend Info:
    Bot Info Name    -> NapCat.Onebot
    Bot Info Version -> 1.6.4
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 457 px
Network Info:
    Github           -> 420 ms
    Link API         -> 86 ms
```

### 更多

非常好客户端，使tx脑瘫qq旋转（）

**Comment by Stapxs** [comment]
napcat 主动获取发送的消息的功能不太可靠，建议去把 napcat 的返回自己的消息开出来。

<img width="566" alt="image" src="https://github.com/user-attachments/assets/16eaf762-18c9-40b0-b6ed-2cc277d9eb6c">

**Comment by MoonLeeeaf** [comment]
谢谢呢~~~修好了（喜）
另外这个Issue应该可以关了（？）
😋😋😋

**Comment by Stapxs** [comment]
😋
