### ISSUE TITLE
[错误] 自动消息类型判断/消息类型对应处理失效

### ISSUE THREAD

**Issue by MoonLeeeaf** [Stapxs/Stapxs-QQ-Lite-2.0#107]
### 错误来源

Stapxs QQ Lite

### 描述错误

它自己会变回 JSON 捏（
![Screenshot_20240715-140138_Via](https://github.com/user-attachments/assets/48ae08da-6224-42a3-acb8-d7145c12c91c)

### 复现流程

1. 设置 - 高级 - 兼容选项 - 消息类型， 设置为任意
2. 刷新页面/重新打开应用
3. 再看一眼，咦？怎么变成JSON辣

### 截图

![Screenshot_20240715-133922_Via](https://github.com/user-attachments/assets/f2dcb9ce-41d3-4c35-b74f-b4bc351e0384)
![Screenshot_20240715-140138_Via](https://github.com/user-attachments/assets/2d056af1-9b54-4aba-bb35-e5f8e4ff2c6a)

### 版本信息

```
Debug Info - 2024/7/15 14:04:09
================================
System Info:
    OS Name          -> Android OS
    Browser Name     -> chrome
    Browser Version  -> 90.0.4430
Application Info:
    Uptime           -> 226805 ms
    Package Version  -> 2.7.13
    Runtime env      -> production
    Service Work     -> true
Backend Info:
    Bot Info Name    -> NapCat.Onebot
    Bot Info Version -> 1.6.4
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 457 px
Network Info:
    Github           -> 1208 ms
    Link API         -> 1779 ms
```

### 更多

喝杯Java压压惊罢（喜）

**Comment by Stapxs** [comment]
自动检测的结果就是 json 所以显示成 json 了（x
逻辑是没错显示确实有点误导就是了

**Comment by MoonLeeeaf** [comment]
> 自动检测的结果就是 json 所以显示成 json 了（x 逻辑是没错显示确实有点误导就是了

不对啊 我发送CQ码的时候也不会识别啊，这不还是JSON么（悲）

另外设在成CQ码什么的刷新也会变成JSON XD

可能是逻辑有点问题力（逃）

**Comment by MoonLeeeaf** [comment]
> 自动检测的结果就是 json 所以显示成 json 了（x 逻辑是没错显示确实有点误导就是了

不对啊 我发送CQ码的时候也不会识别啊，这不还是JSON么（悲）

另外设在成CQ码什么的刷新也会变成JSON（）

可能是逻辑有点问题力（逃）

**Comment by Stapxs** [comment]
> 不对啊 我发送CQ码的时候也不会识别啊，这不还是JSON么（悲）

https://napneko.github.io/zh-CN/guide/config
处不处理 CQCode 是 napcat 的设置决定的，这个设置主要是用来解析收到的是 CQCode 的情况 emmm

不过我发现我这 CQ 码兼容确实也坏了（
疑似由 85db7357d15800d4cce1fe4a2e7d9647c0b4c8bf 一开始做 jsonPath 动态配置文件的时候就坏掉了也没人用 CQCode 一直没发现 XD
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/85db7357d15800d4cce1fe4a2e7d9647c0b4c8bf/src/function/msg.ts#L265-L284

**Comment by Stapxs** [comment]
更新已提交部署，可以康康有没有什么问题然后关掉 issue（瘫

**Comment by MoonLeeeaf** [comment]
目前没问题（摊
谢谢作者（）
