### ISSUE TITLE
是否支持 后端置于服务器连接

### ISSUE THREAD

**Issue by furlingdu** [Stapxs/Stapxs-QQ-Lite-2.0#112]
### 错误来源

None

### 描述错误

如题 目前NapCat运行在服务器上 使用反向ws链接（ws://0.0.0.0:1234/）
在想是否支持本地连接服务器 如本地运行SQL 链接地址填写为ws://公网IP:1234/
实测会直接报错error（

### 复现流程

/

**Comment by Stapxs** [comment]
web 版还是 electron 版（x

**Comment by furlingdu** [comment]
Electron

**Comment by Stapxs** [comment]
electron 的后端化连接在 todo 里正在修改
不过你都挂到公网了不考虑挂个 SSL 么 XD

**Comment by Stapxs** [comment]
dac4a65
