### ISSUE TITLE
archlinux疯狂报错

### ISSUE THREAD

**Issue by gfhdhytghd** [Stapxs/Stapxs-QQ-Lite-2.0#113]
### 错误来源

None

### 描述错误

尝试在archlinux上安装了stapxs,无论是aur还是deb+debtap安装，都是疯狂报错，报错信息如下：
![image](https://github.com/user-attachments/assets/0a6e77a2-d800-4f5f-9200-7f0aca1b6e00)
注：必须在打开应用之后立即进入设置，否则直接卡死无相应

### 复现流程

输入ws和token,点连接

### 版本信息

```
Debug Info - 8/12/2024, 8:24:56 PM
================================
System Info:
    OS Name          -> Linux
    Browser Name     -> chrome
    Browser Version  -> 118.0.5993
    Electron Version -> 27.3.11
Application Info:
    Uptime           -> 246.04 s
    Package Version  -> 2.7.18
    Runtime env      -> production
    Service Work     -> false
Backend Info:
    Bot Info Name    -> NapCat.Onebot
    Bot Info Version -> 1.8.6
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 949 px
Network Info:
    Github           -> 703 ms
    Link API         -> failed
```

**Comment by Stapxs** [comment]
是 arch 用户！
这个报错是个历史遗留 BUG；不过应该不会卡成这样才是，你有多少个群 XD

**Comment by gfhdhytghd** [comment]
> 是 arch 用户！ 这个报错是个历史遗留 BUG；不过应该不会卡成这样才是，你有多少个群 XD

这个号就俩群
补充更多信息：
我的服务端部署在服务器上，ws+http连接,8003端口
昵称和头像可以正常加载，但是剩下的全都不正常，console除了图中这些，剩下一堆403
![image](https://github.com/user-attachments/assets/8c456668-4bd5-466a-bc86-eed1dedbdb5c)

**Comment by gfhdhytghd** [comment]
只要一点击消息列表或者联系人列表，这应用就卡死，cpu占用0%

**Comment by Stapxs** [comment]
怪怪，晚点我看看；可以麻烦看一下网页版的性能正常吗
https://stapxs.github.io/Stapxs-QQ-Lite-2.0/

**Comment by gfhdhytghd** [comment]
这个demo我点连接没反应,似乎是https的问题
![image](https://github.com/user-attachments/assets/68a24856-da1a-46a7-b604-1d7919f7baed)

**Comment by Stapxs** [comment]
那倒是 emmm https 没法连非 wss 的
就酱吧，晚点我看看性能问题（瘫

**Comment by gfhdhytghd** [comment]
让我Syyu一下试试

**Comment by Stapxs** [comment]
版本是最新的啦，感觉确实就是性能问题（

**Comment by gfhdhytghd** [comment]
刚才抽风了一下获取到了一个群的信息，然后又迅速的废了

我还有个小问题，token为空的情况下要怎么登陆？这个onebot后面跟着一屁股东西，之前没开token,现在要全加上token太烦了

**Comment by Stapxs** [comment]
空着直接连接就好（

**Comment by gfhdhytghd** [comment]
报1005

**Comment by gfhdhytghd** [comment]
重启了一下napcat,好了

**Comment by Stapxs** [comment]
疑似为 napcat 1.8.0 对分组功能的修改导致的兼容性错误；解析分组列表导致的死循环过度消耗性能。

等待八月累计更新合并：
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/pull/111

**Comment by Stapxs** [comment]
2a9ed11b593d3be6af2bd2cd0f9272976ad77d27
