### ISSUE TITLE
剪切板图片粘贴发送后无法显示

### ISSUE THREAD

**Issue by huankong233** [Stapxs/Stapxs-QQ-Lite-2.0#116]
### 错误来源

Stapxs QQ Lite（All）

### 描述错误

剪切板图片粘贴发送出去后无法显示

不过重新登陆之后就可以使用qq服务器上的图片就可以正常显示了

### 复现流程

- 使用QQ截图
- 打开软件
- 粘贴并发送

### 截图

![image](https://github.com/user-attachments/assets/4e5e3d3d-479c-4deb-a55c-98ae14e31781)

### 版本信息

```
Debug Info - 2024/8/21 16:48:44
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> chrome
    Browser Version  -> 118.0.5993
    Electron Version -> 27.3.11
Application Info:
    Uptime           -> 21.82 s
    Package Version  -> 2.8.2
    Runtime env      -> production
    Service Work     -> false
Backend Info:
    Bot Info Name    -> NapCat.Onebot
    Bot Info Version -> 2.0.33
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 1200 px
Network Info:
    Github           -> 89 ms
    Link API         -> failed
```

**Comment by Stapxs** [comment]
开一下 napcat 通知自己的消息设置
<img width="255" alt="image" src="https://github.com/user-attachments/assets/e7336094-81bd-4a2a-8e5a-9be9c6c47a8a">

发送消息分了三个阶段：
1. 发送消息本地显示，因为我懒所以本地显示阶段没把发出去的图片贴上来
2. 发送消息返回，这时候加载的圈圈会消失但是消息是灰色的
3. 收到自己消息的 notice 通知，这时候我才会认为消息完整的发出去了并通过这条 notice 显示正确的消息

这么做主要是针对 bot 挂在其他服务器上发送延迟比较大的情况，优先把消息显示出来再确认发送，避免误认为发送操作没成功（
所以灰色但是没加载圈圈大概率是没收到自己的消息 XD

**Comment by huankong233** [comment]
> 开一下 napcat 通知自己的消息设置 <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/42486439/359842025-e7336094-81bd-4a2a-8e5a-9be9c6c47a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzM1MzksIm5iZiI6MTcyNDIzMzIzOSwicGF0aCI6Ii80MjQ4NjQzOS8zNTk4NDIwMjUtZTczMzYwOTQtODFiZC00YTJhLThlNWEtOWJlOWM2YzQ3YThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjNlZmYyMzY2YzIwMDM3Zjg0NGRlYjI3ZTYzOTY1YTZiNTIyNjE0MjdjZWM1MDhiNzFhYzQyMjE3YTg5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6zJPGxapjXbw10chO5gzDB50OMIHVfm8yH0r6DrVkU">

怪不得那个消息是灰色的，原来是用这个来判断消息发没发出去，明白了
