### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by TianMengLucky** [Stapxs/Stapxs-QQ-Lite-2.0#121]
### 适用版本

Stapxs QQ Lite（All）

### 描述请求

1.显示在群聊是否被禁言
2.退群功能
3.NapCat处理好友加群申请

**Comment by Stapxs** [comment]
> 1.显示在群聊是否被禁言

大部分 bot 都没有获取当前群是否可以发言的功能所以没有做（，napcat 好像也不行.png
之前有写了个发言失败自动显示成禁言的功能好像年久失修坏掉了

> 处理好友加群申请

这个其实也有但是估计也因为年久失修坏掉了

**Comment by TianMengLucky** [comment]
![image](https://github.com/user-attachments/assets/85b1f735-7cd4-47b9-96e4-22f42451b1f5)
NapCat有相关上报事件但不知道用不用得了

**Comment by Stapxs** [comment]
嗯 但是就是说首次打开群的时候我没法确定是不是在禁言的状态（x
只有在开着并且收到了通知之后才能知道现在变成禁言了这样
