### ISSUE TITLE
最新版本（Release 2.8.6）不论是Lagrange/LLOneBot/NapCatQQ均无法正常加载联系人页面

### ISSUE THREAD

**Issue by Starry-Sky-World** [Stapxs/Stapxs-QQ-Lite-2.0#126]
### 错误来源

Stapxs QQ Lite（All）

### 描述错误

使用编译的Windows/MacOS/Linux有概率出现报错提示（OneBotv11，LLOnebot/Lagrange）
连接成功后，不会显示联系人
手搓调用获取联系人Api是正常的

### 复现流程

打开2.8.6 版本
- 输入Lagrange/LLOnebot/NapCatQQ连接地址+密钥，点击登录
    （此时有概率发生报错[直接弹窗口]）
- 连接成功后，打开联系人，大概率会像下面那样（或者是只显示群组）（2.7.16版本是正常的）
![image](https://github.com/user-attachments/assets/f0909110-cba5-480e-a193-44cd5adb9544)
- 如果你随机打开了一个群，就会提示加载消息失败，并且无法发送消息（有概率可以）。（2.7.16版本是正常的）

### 截图

![image](https://github.com/user-attachments/assets/750c251d-f702-406e-8974-52a1d3c122df)
![image](https://github.com/user-attachments/assets/61fd897d-d95a-4a34-965f-fb143395194e)

### 版本信息

**提供三个Windows/Web(qq.starryfun.icu)/Web(https://qq.stysusu.top/)
```
Debug Info - 2024/9/22 13:34:47
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> chrome
    Browser Version  -> 118.0.5993
    Electron Version -> 27.3.11
Application Info:
    Uptime           -> 308.99 s
    Package Version  -> 2.8.6
    Runtime env      -> production
    Service Work     -> false
Backend Info:
    Bot Info Name    -> LLOneBot
    Bot Info Version -> 3.27.3
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 1208 px
Network Info:
    Github           -> 1757 ms
    Link API         -> failed
```
```
Debug Info - 2024/9/22 13:35:12
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> edge-chromium
    Browser Version  -> 129.0.0
Application Info:
    Uptime           -> 1495.21 s
    Package Version  -> 2.8.6
    Runtime env      -> production
    Service Work     -> true
Backend Info:
    Bot Info Name    -> Lagrange.OneBot
    Bot Info Version -> 0.0.3
    Loaded Config    -> Lagrange.OneBot
View Info:
    Doc Width        -> 1275 px
Network Info:
    Github           -> 638 ms
    Link API         -> failed
```
```
Debug Info - 2024/9/22 13:35:40
================================
System Info:
    OS Name          -> Windows 10
    Browser Name     -> edge-chromium
    Browser Version  -> 129.0.0
Application Info:
    Uptime           -> 1698.77 s
    Package Version  -> 2.8.6
    Runtime env      -> production
    Service Work     -> true
Backend Info:
    Bot Info Name    -> Lagrange.OneBot
    Bot Info Version -> 0.0.3
    Loaded Config    -> Lagrange.OneBot
View Info:
    Doc Width        -> 1275 px
Network Info:
    Github           -> 778 ms
    Link API         -> failed
```

### 更多

有概率报错弹出（构建的客户端版本，非WEB），没复制...

**Comment by Stapxs** [comment]
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/releases/tag/v2.8.2

2.8 版本不支持 napcat 1.0 了，更新下版本 emmm
其他俩确实没测试得康康

**Comment by Stapxs** [comment]
拉格兰确实有点问题
llob 的带分组的好友列表没有更新成 napcat 那种格式所以出了点问题 🤔

**Comment by Starry-Sky-World** [comment]
嘶...我是LLOnebot

**Comment by Starry-Sky-World** [comment]
> 拉格兰确实有点问题 llob 的带分组的好友列表没有更新成 napcat 那种格式所以出了点问题 🤔

修复了踢我一脚，马上来编译web端（）

**Comment by Stapxs** [comment]
顺带一提如果要部署在根目录下，web 端也有构建好的.png
<img width="297" alt="image" src="https://github.com/user-attachments/assets/1c44c1b5-4a5b-4fca-83d6-31644a6733ec">

**Comment by Starry-Sky-World** [comment]
> 顺带一提如果要部署在根目录下，web 端也有构建好的.png <img alt="image" width="297" src="https://private-user-images.githubusercontent.com/42486439/370085685-1c44c1b5-4a5b-4fca-83d6-31644a6733ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODc5NzgsIm5iZiI6MTcyNzI4NzY3OCwicGF0aCI6Ii80MjQ4NjQzOS8zNzAwODU2ODUtMWM0NGMxYjUtNGE1Yi00ZmNhLTgzZDYtMzE2NDRhNjczM2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE4MDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGI0OGIyMDRmZGUyYTMzYjA5NzRkZTI4MGNlNDMyZTA2ODRmZTdlNWQzMTNmMDI4ZjIzNzYxN2IyYjliOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fUCj8e2-_GqKGCs9vBjEyIfFMMyitJCMpvDJMsXDgXc">

so，什么时候开发防撤回,jpg

**Comment by Stapxs** [comment]
> llob 的带分组的好友列表没有更新成 napcat 那种格式所以出了点问题

LLOneBot 3.33.8 把接口改成一样的了，改了代码又给改回去了 XD
