### ISSUE TITLE
2.9.0在windows上似乎启动不了

### ISSUE THREAD

**Issue by dev-soragoto** [Stapxs/Stapxs-QQ-Lite-2.0#130]
### 错误来源

Stapxs QQ Lite（Electron）

### 描述错误

会卡在毛玻璃效果那一页不动……我也不知道怎么查日志

### 复现流程

下载 运行 卡住

### 截图

![image](https://github.com/user-attachments/assets/9d3fea58-13a3-45e2-afa4-510428e6b4d8)

### 版本信息

2.9.0

版本	Windows 11 专业工作站版
版本号	23H2
安装日期	‎2024/‎5/‎31
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by Stapxs** [comment]
fix 2.9.1

**Comment by dev-soragoto** [comment]
> fix 2.9.1

好快的修！

**Comment by Stapxs** [comment]
> > fix 2.9.1
> 
> 好快的修！

已经摸了三天了（x

**Comment by dev-soragoto** [comment]
> > > fix 2.9.1
> > 
> > 
> > 好快的修！
> 
> 已经摸了三天了（x

是我我肯定会摸到上班的时候摸鱼修（不是
