### ISSUE TITLE
icalingua 协议兼容

### ISSUE THREAD

**Issue by Stapxs** [Stapxs/Stapxs-QQ-Lite-2.0#131]
### 适用版本

Stapxs QQ Lite（All）

### 描述请求

对 icalingua-oicq 的兼容计划。 -> https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/76#issuecomment-2323383959 @shenjackyuanjie

**Comment by shenjackyuanjie** [comment]
好耶（

**Comment by Stapxs** [comment]
icalingua-oicq 不支持标准 onebot 协议暂时放弃支持计划

**Comment by shenjackyuanjie** [comment]
悲伤（也许我可以写个兼容层呢
辛苦啦~
