### ISSUE TITLE
oicq仓库疑问

### ISSUE THREAD

**Issue by VirgilG72** [Stapxs/Stapxs-QQ-Lite-2.0#132]
大佬 我看到你在这里的提问https://github.com/whitechi73/OpenShamrock/issues/44
里面提到了这个链接https://find.qq.com/proxy/domain/cgi.find.qq.com/qqfind/find_v11?backver=2 
这个获取qq签名接口是否失效了？
我这边构造了post请求访问是500服务不可用，你那边能请求成功？
或者还有别的获取QQ个性签名的方法吗？提前感谢大佬回复

**Comment by Stapxs** [comment]
find.qq.com 域下的部分接口貌似确实没掉了 🤔 我没用它不知道有啥替代接口 😮‍💨

**Comment by VirgilG72** [comment]
> find.qq.com 域下的部分接口貌似确实没掉了 🤔 我没用它不知道有啥替代接口 😮‍💨

对的 其他的我也能用；比如这个查询基本信息的：
https://find.qq.com/proxy/domain/cgi.find.qq.com/qqfind/buddy/search_v3?
但是查详细信息（含个性签名）的接口 访问不了QAQ
你那边有试过请求吗 不知道是不是我构造post请求的方式不对QAQ

**Comment by Stapxs** [comment]
> 你那边有试过请求吗 不知道是不是我构造post请求的方式不对QAQ

我试了下貌似也是爆炸的 😭
