### ISSUE TITLE
手机网页端出现严重错误

### ISSUE THREAD

**Issue by Starrain08** [Stapxs/Stapxs-QQ-Lite-2.0#134]
### 错误来源

Stapxs QQ Lite（Web）

### 描述错误

手机网页端显示错误

### 复现流程

使用手机端访问网页查看消息

### 截图

![b1fd4bb3a5ca4c57aabb23e87c20d859](https://github.com/user-attachments/assets/53113c83-92f1-4542-967c-f01d5fe12280)

### 版本信息

Debug Info - 2024/10/24 21:16:49
================================
System Info:
    OS Name          -> iOS
    Browser Name     -> ios
    Browser Version  -> 17.3.1
Application Info:
    Uptime           -> 453.3 s
    Package Version  -> 2.9.2
    Runtime env      -> production
    Service Work     -> undefined
Backend Info:
    Bot Info Name    -> NapCat.Onebot
    Bot Info Version -> 3.1.5
    Loaded Config    -> NapCat.Onebot
View Info:
    Doc Width        -> 487 px
Network Info:
    Github           -> 3 ms
    Link API         -> failed

**Comment by Stapxs** [comment]
虽然疑似图片查看器的 css 裂开了，但是没复现出来 🤔
暂且关闭如果还遇到了再开.gif

**Comment by Starrain08** [comment]
e,2.9.3网页bug还在
