### ISSUE TITLE
赛博灯泡

### ISSUE THREAD

**Issue by TianMengLucky** [Stapxs/Stapxs-QQ-Lite-2.0#142]
### 适用版本

Stapxs QQ Lite（Web）

### 描述请求

林老师，限制一下设置缩放比例，或者整个什么能还原的，要不然误触缩放直接变成赛博灯泡，如图

### 截图

![Screenshot_20241122_162441](https://github.com/user-attachments/assets/716bf089-2582-41ef-b8c2-27dc0dd95bda)

**Comment by Stapxs** [comment]
噫—— 哈人，先临时清除网页数据解决吧 😭
