### ISSUE TITLE
赛博灯泡

### ISSUE THREAD

**Issue by FfmpegZZZ** [Stapxs/Stapxs-QQ-Lite-2.0#143]
### 错误来源

Stapxs QQ Lite（All）

### 描述错误

![image](https://github.com/user-attachments/assets/2e57b0ca-592c-4b3b-8c6a-1c7eb161a56e)

### 复现流程

转过来之后关闭设置页面就回不去了

**Comment by FfmpegZZZ** [comment]
右上角很难重新点到设置（
**_重启也没用（_**

**Comment by Stapxs** [comment]
没考虑到 win 顶上有个栏
这下彩蛋变 BUG 了
