### ISSUE TITLE
本地打包和调试背景似乎变成了全透明

### ISSUE THREAD

**Issue by dev-soragoto** [Stapxs/Stapxs-QQ-Lite-2.0#151]
### 错误来源

Stapxs QQ Lite（All）

### 描述错误

最新的代码本地打包似乎有一些问题……

### 复现流程

yarn

yarn dev
![屏幕截图_20241205_132818](https://github.com/user-attachments/assets/97f29afd-4a3a-4501-ae60-804d41d46905)

yarn dev:electron
![屏幕截图_20241205_132909](https://github.com/user-attachments/assets/c51c37c7-2863-4304-a707-2209fe1a786b)

**Comment by dev-soragoto** [comment]
悲 还有新问题 linux版本上终端皮肤变成了全透明 
![image](https://github.com/user-attachments/assets/aced2a7e-2d5d-4cc0-b5fd-0ddea1df445c)

**Comment by dev-soragoto** [comment]
我似乎最开始只是想手动改一下联系人下面那个搜索框的位置好水一个pr来着——

**Comment by Stapxs** [comment]
emmm 项目的子模块位置有变更，如果是我大改之前就 clone 的仓库得重新初始化下子仓库或者干脆重新 clone 下

**Comment by dev-soragoto** [comment]
> emmm 项目的子模块位置有变更，如果是我大改之前就 clone 的仓库得重新初始化下子仓库或者干脆重新 clone 下

我是新clone的 显然……

**Comment by Stapxs** [comment]
那看一眼 ``` src/renderer/public/bcui ``` 和 ``` src/renderer/src/assets/img/qq-face ``` 里面有没有东西（

**Comment by dev-soragoto** [comment]
> 那看一眼 `src/renderer/public/bcui` 和 `src/renderer/src/assets/img/qq-face` 里面有没有东西（

哦哦哦我忘记submodule了！

**Comment by dev-soragoto** [comment]
> 那看一眼 `src/renderer/public/bcui` 和 `src/renderer/src/assets/img/qq-face` 里面有没有东西（

不过那个shell皮肤似乎是真的坏了（

**Comment by Stapxs** [comment]
> 不过那个shell皮肤似乎是真的坏了（

linux 没做测试手头也暂时没环境 🤔 得今天回去再看看了

**Comment by Stapxs** [comment]
> 不过那个shell皮肤似乎是真的坏了（

噫 是我忘记改了——
动态导入的页面不会被 eslint 和脚手架扫到<sub>（会被认为是没被调用的文件）</sub>，导致我遗漏掉了

**Comment by dev-soragoto** [comment]
> 不过我没确定为什么这次会这样

> 啊啊啊 我怎么又点成编辑了 😭

**Comment by Stapxs** [comment]
> 不过我没确定为什么这次会这样

可能是我写手机版的 css 的时候反向改回去的样式有点问题 🤔
有些我觉得可以改到共用 css 里的东西我改进去了可能搞烂了些啥 XD

加完最好检查下 web 和 electron 都没问题，手机版的只有 iOS 不方便就先不管它

**Comment by dev-soragoto** [comment]
> > 不过我没确定为什么这次会这样
> 
> 可能是我写手机版的 css 的时候反向改回去的样式有点问题 🤔 有些我觉得可以改到共用 css 里的东西我改进去了可能搞烂了些啥 XD
> 
> 加完最好检查下 web 和 electron 都没问题，手机版的只有 iOS 不方便就先不管它

好的我先去检查一下（

**Comment by TianMengLucky** [comment]
> ### 错误来源
> Stapxs QQ Lite（All） Stapxs QQ Lite（全部）
> 
> ### 描述错误
> 最新的代码本地打包似乎有一些问题……
> 
> ### 复现流程
> yarn 纱
> 
> yarn dev 纱线开发 ![屏幕截图_20241205_132818](https://private-user-images.githubusercontent.com/43477078/392669459-97f29afd-4a3a-4501-ae60-804d41d46905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDY4NDAsIm5iZiI6MTczMzQwNjU0MCwicGF0aCI6Ii80MzQ3NzA3OC8zOTI2Njk0NTktOTdmMjlhZmQtNGEzYS00NTAxLWFlNjAtODA0ZDQxZDQ2OTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEzNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTM0OWY5YmU2YjEzMmI0MzAwNjliYTFiYjMxMDE2NzUxNzA3YWJlZjkzODU1OGVkZDU1NTlmMzQwNjg3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.icXz2FJ1IxU_eUmuDBZesHHGDzCUlIYVPL5ouW-QZ3k)
> 
> yarn dev:electron 纱线开发：electron ![屏幕截图_20241205_132909](https://private-user-images.githubusercontent.com/43477078/392669487-c51c37c7-2863-4304-a707-2209fe1a786b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDY4NDAsIm5iZiI6MTczMzQwNjU0MCwicGF0aCI6Ii80MzQ3NzA3OC8zOTI2Njk0ODctYzUxYzM3YzctMjg2My00MzA0LWE3MDctMjIwOWZlMWE3ODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEzNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTEzOGE0Y2YyNTM4ZmFmMGVjOTc3YzQzODE3NTQ0MWJjYmM3YjdhODc5YmIxYWFmMzA3MDY5OTc0MjZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ccuOuLBTxAQx75i6Lj-KJcu7xhDqsOMofihfG83jvK4)
> 
> ### 截图
> _No response 无响应_
> 
> ### 版本信息
> _No response 无响应_
> 
> ### 更多
> _No response 无响应_

是这样的，前几天我看也觉得离谱，删掉重新clone主仓库下来又突然好了

**Comment by dev-soragoto** [comment]
> > ### 错误来源
> > Stapxs QQ Lite（All） Stapxs QQ Lite（全部）
> > ### 描述错误
> > 最新的代码本地打包似乎有一些问题……
> > ### 复现流程
> > yarn 纱
> > yarn dev 纱线开发 ![屏幕截图_20241205_132818](https://private-user-images.githubusercontent.com/43477078/392669459-97f29afd-4a3a-4501-ae60-804d41d46905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDY4NDAsIm5iZiI6MTczMzQwNjU0MCwicGF0aCI6Ii80MzQ3NzA3OC8zOTI2Njk0NTktOTdmMjlhZmQtNGEzYS00NTAxLWFlNjAtODA0ZDQxZDQ2OTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEzNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTM0OWY5YmU2YjEzMmI0MzAwNjliYTFiYjMxMDE2NzUxNzA3YWJlZjkzODU1OGVkZDU1NTlmMzQwNjg3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.icXz2FJ1IxU_eUmuDBZesHHGDzCUlIYVPL5ouW-QZ3k)
> > yarn dev:electron 纱线开发：electron ![屏幕截图_20241205_132909](https://private-user-images.githubusercontent.com/43477078/392669487-c51c37c7-2863-4304-a707-2209fe1a786b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDY4NDAsIm5iZiI6MTczMzQwNjU0MCwicGF0aCI6Ii80MzQ3NzA3OC8zOTI2Njk0ODctYzUxYzM3YzctMjg2My00MzA0LWE3MDctMjIwOWZlMWE3ODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEzNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTEzOGE0Y2YyNTM4ZmFmMGVjOTc3YzQzODE3NTQ0MWJjYmM3YjdhODc5YmIxYWFmMzA3MDY5OTc0MjZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ccuOuLBTxAQx75i6Lj-KJcu7xhDqsOMofihfG83jvK4)
> > ### 截图
> > _No response 无响应_
> > ### 版本信息
> > _No response 无响应_
> > ### 更多
> > _No response 无响应_
> 
> 是这样的，前几天我看也觉得离谱，删掉重新clone主仓库下来又突然好了

后面发现是我忘记子模块了…不行我要把这个issue关了 不然显得我很呆

**Comment by Stapxs** [comment]
> 后面发现是我忘记子模块了…不行我要把这个issue关了 不然显得我很呆

其实我还特地写在 README 里了（x
主要是因为子模块依赖的是一堆 CSS 和一堆表情，没掉了看着和出了啥 BUG 似的
