### ISSUE TITLE
[功能请求]请问是否考虑增设docker部署？

### ISSUE THREAD

**Issue by CiaoFox** [Stapxs/Stapxs-QQ-Lite-2.0#154]
如题，对我这种脑子不太好的人来说docker部署是一种省力到极点的部署方式，清洁，快速，启动停用都很方便。所以冒昧想请求作者增加docker部署的方式。
另外Github action可以快速部署到docker hub，您每次更新之后可以直接action自动部署新容器，省去维护精力。

**Comment by Stapxs** [comment]
项目支持使用 npx 部署，如果你系统上装了 nodejs；可以直接使用 npx 工具快速启动 🤔
感觉写个 docker 镜像有点大材小用 XD

包管理安装和快速部署提醒 -> https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/99

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/4fc0a1fc-eac3-4b0c-827a-6a75844b369a">

**Comment by Stapxs** [comment]
https://hub.docker.com/repository/docker/stapxs/qq-web

**Comment by CiaoFox** [comment]
感谢。
