### ISSUE TITLE
[错误]开启「通知所有新消息」后新消息会显示在已经置顶的会话之上

### ISSUE THREAD

**Issue by Logic-Accepted** [Stapxs/Stapxs-QQ-Lite-2.0#16]
**描述错误**

**复现流程**

**截图**

![sql2](https://user-images.githubusercontent.com/36406453/209432513-37dda9f1-0e68-4498-9223-1b1e56673e59.png)

**版本信息**

1 - 2.1.1
2 - chrome
3 - 106.0.5249
4 - Linux
**更多**

**Comment by Stapxs** [comment]
复现失败
PS：新添加的置顶不会马上生效需要刷新页面，下版本将会修复
