### ISSUE TITLE
[错误] 在輸入框輸入消息後，文字自動消失。

### ISSUE THREAD

**Issue by wuxian425** [Stapxs/Stapxs-QQ-Lite-2.0#24]
**描述错误**

 在輸入框輸入消息後，文字自動消失。

**复现流程**

隨便點一個群，然後輸入文字。

**截图**

**版本信息**

![圖片](https://user-images.githubusercontent.com/82699919/211534818-24ceb8b3-c6b8-4791-a968-17da65ae964d.png)

**更多**

輸入法是 RIME 和 新注音2003 的中文模式，英文模式則可正常輸入發送，新注音2003 待選狀態時點擊發送也可正常發送。

**Comment by Stapxs** [comment]
在 firefox 下输入法回车选词会有问题 emmm

**Comment by wuxian425** [comment]
> 在 firefox 下输入法回车选词会有问题 emmm 会直接触发回车发送导致没选上词

並沒有發送來著（

**Comment by Stapxs** [comment]
2.2.2 - 已尝试修正问题，请检查是否有效 XD

**Comment by wuxian425** [comment]
> 2.2.2 - 已尝试修正问题，请检查是否有效 XD

没有（

**Comment by Stapxs** [comment]
emmm 确认是 2.2.2 版本么（捂脸
那就有点难搞我晚点试试复现

**Comment by wuxian425** [comment]
> emmm 确认是 2.2.2 版本么（捂脸 那就有点难搞我晚点试试复现

强制刷新过了，更新日志也显示出来了，应该是的

**Comment by wuxian425** [comment]
测试 1ceb290 修正无效（

**Comment by Stapxs** [comment]
> 测试 [1ceb290](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/commit/1ceb2900f80933a6becb98693feaa235110181ac) 修正无效（

摆烂了（无端

**Comment by wuxian425** [comment]
> > 测试 [1ceb290](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/commit/1ceb2900f80933a6becb98693feaa235110181ac) 修正无效（
> 
> 摆烂了（无端

（恼

**Comment by Stapxs** [comment]
![image](https://user-images.githubusercontent.com/42486439/215930681-6264b813-b9fb-46e9-846d-92c9e5d642cf.png)
摆烂了（再次
![image](https://user-images.githubusercontent.com/42486439/215930729-645e31b7-8e86-46dd-9d14-191252fe7289.png)

**Comment by wuxian425** [comment]
于是死守旧版（

**Comment by Stapxs** [comment]
2.2.6 - 在设置中增加了 启用shift换行 的选项并默认关闭了这个功能来解决奇怪的输入法问题 ……，现在默认不允许 shift 换行但是应该不会出现奇奇怪怪的输入问题了

请检查更改是否有效 XD

**Comment by wuxian425** [comment]
RIME 测试：Shift 换行开启与否都没问题
新注音 2003 测试：Shift 换行开启与否都没问题
旧注音测试：Shift 换行开启与否都没问题
拼音新体验：Shift 换行开启与否都没问题
