### ISSUE TITLE
收到的消息会显示多次，重新加载对话框后会正常。接收到的新消息又会重复显示[错误]

### ISSUE THREAD

**Issue by DeasonHu** [Stapxs/Stapxs-QQ-Lite-2.0#26]
**描述错误**

当你与好友聊天的时候，好友给你发了一条消息，你这里会重复显示他发的消息
**复现流程**

它可能是远程部署 wss 特有的问题，因为我猜测其他人都是在本地部署的，oicq 和前端延迟比较低可能就没有出现这个问题
不过这是猜测，我暂时没有时间尝试本地 ws。我会在最近一周再补充些相关的信息。
1. 找个人，让他给你发个消息即可复现
**截图**

![屏幕截图 2023-01-11 140231](https://user-images.githubusercontent.com/78863300/211731229-eef42814-8ed6-4fc9-8b89-6d13215beb3c.png)
**版本信息**

1 - 2.1.9
2 - edge-chromium
3 - 108.0.1462
4 - Windows 10
我是 Windows 11 不是 Windows 10
**更多**

截图中的控制台报错我看了，好像和这个问题没什么关系。

**Comment by Stapxs** [comment]
原因已确定 …… 因为各种原因连接不及时导致你按了好几下连接按钮 or 其他原因，总之问题是连接了多次 websocket 导致的（

**Comment by DeasonHu** [comment]
谢谢 明白了
