### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by miangou** [Stapxs/Stapxs-QQ-Lite-2.0#30]
**描述错误**

发出文字空白
**复现流程**

Windows下回车~
**截图**

没有欸
**版本信息**

**更多**

**Comment by Stapxs** [comment]
啥浏览器 emmmm

**Comment by miangou** [comment]
> 啥浏览器 emmmm

chrome

**Comment by DeasonHu** [comment]
> > 啥浏览器 emmmm
> 
> chrome

![图片](https://user-images.githubusercontent.com/78863300/213617054-2dc54d90-d665-4677-b40f-78b021010699.png)

**Comment by miangou** [comment]
版本 109.0.5414.75（正式版本） （64 位）

**Comment by DeasonHu** [comment]
https://cloud.senint.net/s/N0Ck
复现失败

**Comment by Stapxs** [comment]
2.2.2 - 已尝试修正问题，请检查是否有效 emmm

**Comment by Stapxs** [comment]
2.2.6 - 在设置中增加了 启用shift换行 的选项并默认关闭了这个功能来解决奇怪的输入法问题 ……，现在默认不允许 shift 换行但是应该不会出现奇奇怪怪的输入问题了

请检查更改是否有效 XD

**Comment by wuxian425** [comment]
所以說這個 issues 不是和我的重疊了嗎（？

**Comment by Stapxs** [comment]
> 所以說這個 issue 不是和我的重疊了嗎（？

他给我的信息没法确认问题是不是同一个（
所以需要等一个确认
