### ISSUE TITLE
opt_auto_dark 似乎是假的[错误]

### ISSUE THREAD

**Issue by DeasonHu** [Stapxs/Stapxs-QQ-Lite-2.0#33]
**描述错误**
自动深色模式 似乎没有工作

**复现流程**
尝试修改系统时间/时区/经纬度/系统深/浅色，QQ Lite 的深色模式仍然会保持上一次的状态

**截图**
![图片](https://user-images.githubusercontent.com/78863300/213620235-26d481ac-dffc-4686-b919-a326a8752daf.png)
将就着看吧，没找到啥有价值的信息

**版本信息**
v2.2.1
Windows11 Workstation 22623.1180
Chromium Edge 版本 109.0.1518.55 (正式版本) (64 位)
但在 Firefox Nightly 111.0a1 (2023-01-19) (64 位) 也可以复现
你怎么能把版本信息给删了呢（（（

**更多**
我翻遍了你的代码，没有找到 opt_auto_dark 字段（至少 App.vue 是没有的）
悄咪咪的问一句 是没做吗（（（
option.ts 68-74 行
`function setDarkMode(value: boolean) {
    if (value === true) {
        changeColorMode('dark')
    } else {
        changeColorMode('light')
    }
}`
我猜或许可以从这里下手（

**Comment by DeasonHu** [comment]
其实还有一个很影响体验的问题 但不需要修
当显卡是 NVIDIA GeForce 9500 GT 时
它有小概率会让显卡挂掉（（
不过明天我就换显卡了

**Comment by Stapxs** [comment]
其实自动暗黑模式的代码在 https://api.stapxs.cn/js/auto-theme.js 我当初迁移 ts 的时候这部分没挪 …… 用也是可以用的就是你一旦动过主动设置颜色模式它就废了（因为我忘记写判断了）

版本信息挪到高级设置里去了 (1f2d21b7c5fe53c23958bd38d07c16f0957a9681)

**Comment by Stapxs** [comment]
关闭自动暗黑模式之后忘记取消监听事件了
