### ISSUE TITLE
关于多端同步聊天记录

### ISSUE THREAD

**Issue by DeasonHu** [Stapxs/Stapxs-QQ-Lite-2.0#38]
qq lite 是不可能做到端和端之间通信的，没有同步聊天记录也可以理解
但我有一个想法，使用数据库来存储数据，而不只是 cookies 之类的了
每条消息都丢进数据库里 每次打开都同步一下 也许使用体验会好很多 不过这样使用者铁定要台服务器了

-------- 分割线 --------

我觉得要加这个功能可能得在 QQ lite v3 了（）
我想的实现方法是把数据库装在 oicq 的服务器上 获取消息就存入数据库，而 qqlite 不再和 oicq 建立连接 而是和数据库建立连接 这样能实现很多很多现在做不了的功能，也不会因为 oicq 的小 bug 导致 qqlite 有问题还修不了（比如私信看不到自己的消息）

大概就是这样吧 我努努力学下 JavaScript 和 Python 争取早日做点贡献（

**Comment by Stapxs** [comment]
web 没法直接连数据库 …… （或者说不建议直接让前端连数据库）
这样的话就可能要写 electron 应用了（

**Comment by Stapxs** [comment]
以及消息通知是通知型的事务 …… 
如果不连接 oicq 的话，新消息难道只靠反复读取数据库来判断么 emmmm
这样感觉数据库压力有点大（无端

**Comment by ctaoist** [comment]
我在go-cqhttp中增加的`get_msg_history`接口就是从数据库中获取消息，不过2.0离兼容go-cqhttp还遥遥无期啊 @Stapxs

**Comment by daofeng2015** [comment]
> 我在go-cqhttp中增加的`get_msg_history`接口就是从数据库中获取消息，现在也兼容 go-cqhttp

问下go-cqhttp应该设置ws为那个模式?正还是反的?

**Comment by Stapxs** [comment]
> > 我在go-cqhttp中增加的`get_msg_history`接口就是从数据库中获取消息，现在也兼容 go-cqhttp
> 
> 
> 
> 问下go-cqhttp应该设置ws为那个模式?正还是反的?

正向

**Comment by ctaoist** [comment]
> > 我在go-cqhttp中增加的`get_msg_history`接口就是从数据库中获取消息，现在也兼容 go-cqhttp
> 
> 问下go-cqhttp应该设置ws为那个模式?正还是反的?

需要用 https://github.com/ctaoist/go-cqhttp 这个仓库的 cdev 分支进行编译

**Comment by Stapxs** [comment]
issue 陈旧，请在有必要的时候重新打开
