### ISSUE TITLE
关于多端支持的计划

### ISSUE THREAD

**Issue by ctaoist** [Stapxs/Stapxs-QQ-Lite-2.0#40]
1. 不清楚现在对 go-cqhttp 支持的进度如何，作者的思路又是啥，可以讨论讨论，我有点等不及了，也可以帮忙写一点，我的思路是在 connetor 类中进行处理转换

2. 登录界面希望可以增加一个选后端的下拉框，选取 oicq1，2，go-cqhttp，其他后端等等

**Comment by Stapxs** [comment]
go-cqhttp 已经可用，但是我没做过多的测试，你可以试试看有问题就丢 issue.

cq code 会在消息处理过程中被转换成 oicq 式的消息格式（新消息处理：[msg.ts#L495](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/2264f71d8a7b5e5644427bbc20209fa924e10b7b/src/function/msg.ts#L495)）（转换方法：[util.ts#L273](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/2264f71d8a7b5e5644427bbc20209fa924e10b7b/src/function/util.ts#L273)），所以理论上说扁平 CQ 码的 onebot 11 的 bot 也全都可以拿出来试试（，至少显示消息部分是没有问题放

后端类型我现在是在代码里写死了判断兼容的几个自动切换的 emmm（判断位置：[msg.ts#L102](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/2264f71d8a7b5e5644427bbc20209fa924e10b7b/src/function/msg.ts#L102)）

**Comment by ctaoist** [comment]
我现在测试结果是只能连接，发消息都发不了

**Comment by Stapxs** [comment]
![图片](https://user-images.githubusercontent.com/42486439/216240096-a3feac22-fb7c-4e73-9c4b-d600dc0aed08.png)
我这貌似没啥问题 emmm 有啥报错么

**Comment by ctaoist** [comment]
每次报的还不太一样
![image](https://user-images.githubusercontent.com/14012127/216240500-a4b3f4d0-15a3-4e50-a9f4-1c1ca5b02de6.png)

**Comment by ctaoist** [comment]
加个联系方式？

**Comment by Stapxs** [comment]
emmm 先确认下版本，在设置界面的底栏有
![图片](https://user-images.githubusercontent.com/42486439/216241036-3219886b-7390-4f79-a72b-bdf8c644df6d.png)

然后我想看一下收到的消息内容，把 设置-高级-日志等级 切换成全部然后随便抡一条，像是这样的
![图片](https://user-images.githubusercontent.com/42486439/216241623-72d108fc-e58d-4b98-99bb-2ab998e1e943.png)

**Comment by Stapxs** [comment]
> 加个联系方式？

https://t.me/Stapx_Steve

**Comment by Stapxs** [comment]
[] go-cqhttp - 有方括号，换行的消息不能正常渲染
[] go-cqhttp - 昵称重复
[] go-cqhttp - 忽略心跳
[] 不是今天的消息希望能够加上日期，便于区分
[] go-cqhttp - 标记已读接口
