### ISSUE TITLE
【建议】回车的时候那个有点点小变扭

### ISSUE THREAD

**Issue by NatsumiXD** [Stapxs/Stapxs-QQ-Lite-2.0#46]
回车的时候有点点小别扭，需要到下一行才会发送消息（（（（
具体视频效果长这样——
[QQ录屏20230228223613.zip](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/files/10851339/QQ.20230228223613.zip)

谢谢啦——（（（

**Comment by Stapxs** [comment]
这个我不知道要怎么修 emmm
如果你实在看着难受可以先把 shift enter 换行关了，不过这样就不能发多行了（无端
