### ISSUE TITLE
[错误]新消息的bug

### ISSUE THREAD

**Issue by miangou** [Stapxs/Stapxs-QQ-Lite-2.0#47]
**描述错误**

**复现流程**

**截图**
[1677595307953.zip](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/files/10851419/1677595307953.zip)

**版本信息**
110.0.5481.178 (正式版本) （64 位） (cohort: Stable) 

**更多**
莫有

**Comment by miangou** [comment]
<html>
<body>


Google Chrome | 110.0.5481.178 (正式版本) （64 位） (cohort: Stable)
-- | --



</body>
</html>

**Comment by miangou** [comment]
<html>
<body>


操作系统 | Windows 10 Version 22H2 (Build 19045.2604)
-- | --



</body>
</html>

**Comment by miangou** [comment]
<html>
<body>


JavaScript | V8 11.0.226.16
-- | --



</body>
</html>

**Comment by miangou** [comment]
<html>
<body>


用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
-- | --



</body>
</html>

**Comment by Stapxs** [comment]
oicq2 的自动返回发送的消息的功能不支持私聊，所以在私聊下这功能会有点问题 …… 我不打算做特殊判断 emmm

所以要么关了这功能：
![图片](https://user-images.githubusercontent.com/42486439/222034759-bd4240f7-8149-4240-b8d5-e31c543ae88c.png)
将 `ignore_self` 改为 `true`
![图片](https://user-images.githubusercontent.com/42486439/222034846-c61c075b-4288-4119-a92d-1487433f0f58.png)
关闭停止消息回调

或者就只能忍着了（无端

**Comment by miangou** [comment]
感谢
