### ISSUE TITLE
[ 提醒 ] 关于 oicq 版本过低问题

### ISSUE THREAD

**Issue by Stapxs** [Stapxs/Stapxs-QQ-Lite-2.0#49]
由于腾讯对最低可用版本下限进行了调整，目前 oicq 当前版本已无法正常登陆。
如果你正在使用我们魔改的 oicq2-http 服务，请直接更新仓库以应用新的更改，我们将 oicq 迁移为了它的 fork [icqq](https://github.com/icqqjs/icqq)，这个分支维护更加活跃并且可以正常使用。

如果你不想迁移或者还在使用旧的 oicq1-http,你可以参见以下 issue 手动解决：
https://github.com/takayama-lily/oicq/issues/451

或者，go-cqhttp 当前也已支持！

**Comment by citydirector** [comment]
https://github.com/icqqjs/icqq

**Comment by Stapxs** [comment]
> https://github.com/icqqjs/icqq

已更新
