### ISSUE TITLE
[错误]关于一些显示上的小问题和界面操作体验改进

### ISSUE THREAD

**Issue by 13130200183** [Stapxs/Stapxs-QQ-Lite-2.0#51]
## **描述错误**
· 联系人列表中联系人依然会部分重复 （修了 但只修了一点（？）
· 私聊会话发送的消息不会实时出现在消息列表 
具体表现为敲下回车 消息栏的文字消失了但仿佛什么也没发生 
实际上消息正常发送 切换会话对象再切回来 刚刚发送的消息也会正常显示 
**群聊没有这个问题（why？）**

## **体验优化（别逼我跪下来求你...）**
· （重要）会话列表支持点选UI快捷切换会话对象 而不是想换人聊天必须去翻联系人列表
（当我点了消息列表的头像发现没切过去一度以为哪里报错了=-=|||）
· 会话列表支持单独会话删除 想定ui表现为长按出现二级列表 【置顶，设为已读，关闭会话】
· 联系人列表支持按好友分组查看 （分组编辑和移动可以搁置 先有分组显示） 

**更多**
为大佬献上膝盖 这个项目简直是上班摸鱼人的宝藏（公司电脑不让装qq）

**Comment by 13130200183** [comment]
换了个qq号又测了一下 会话列表点选UI可以切换了 消息也能实时显示了 很迷...

**Comment by Stapxs** [comment]
- 联系人重复可能是重新连接 BUG emmm 因为没怎么复先出来过所以没管
- 私聊消息不回显是因为 oicq 返回发送消息的功能只支持群聊，你可以干脆把这个功能关了让 sql2 自己获取
- 会话列表可以切换啊难不成的 BUG
- 因为我懒得做菜单所以会话列表目前右击是设为已读，置顶目前在群/好友信息的菜单里；这个之后做了菜单会改
- oicq 没法取得分组信息所以没法做分组

**Comment by Stapxs** [comment]
- [ ] （疑似 BUG）会话列表点击异常
- [ ] 重连后程序状态检查（优化重连）
- [ ] 部分组件换用新写的封装组件（顺便把会话列表的右击菜单做了）

**Comment by 13130200183** [comment]
> * 联系人重复可能是重新连接 BUG emmm 因为没怎么复现出来过所以没管
> * 私聊消息不回显是因为 oicq 返回发送消息的功能只支持群聊，你可以干脆把这个功能关了让 sql2 自己获取 -> [[错误]新消息的bug #47 (comment)](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/47#issuecomment-1449265291)
> * 会话列表可以切换啊难不成是 BUG
> * 因为我懒得做菜单所以会话列表目前右击是设为已读，置顶目前在群/好友信息的弹窗里；这个之后做了菜单会改
> * oicq 没法取得分组信息所以没法做分组

![image](https://user-images.githubusercontent.com/54051043/230807175-750955e2-0f1d-4a48-81df-13a3c1f65deb.png)
> *  oicq 请求好友列表的时候会附带返回所在分组信息 把这个数据处理一下应该能够实现

**Comment by Stapxs** [comment]
诶 …… 没有 class_name XD
我就是因为没名字所以才没做的 emmm
不知道是 oicq 疏漏没做还是啥的总之它貌似确实没有返回名字

![图片](https://user-images.githubusercontent.com/42486439/230854021-e388c3d8-0ed7-4b60-a7b1-adad687e361c.png)

**Comment by Stapxs** [comment]
![图片](https://user-images.githubusercontent.com/42486439/231029752-7728043f-003b-48bb-a5aa-66a4fb164535.png)
简单看了下代码它确实是没写 class_name …… 我看看能不能修好

**Comment by Stapxs** [comment]
TODO：
- [ ] 消息列表右击菜单（重构部分组件换用新的 UI 库）
- [ ] 好友列表重构实现分组相关功能

**Comment by 13130200183** [comment]
接口很好用！孩子很爱吃！！大声）
![image](https://user-images.githubusercontent.com/54051043/231740062-6eed9667-9ec2-4f45-861e-61eb4f84251e.png)
