### ISSUE TITLE
[求助]如何使用密码登录呢？

### ISSUE THREAD

**Issue by FengziLeo** [Stapxs/Stapxs-QQ-Lite-2.0#54]
扫码每次都会提示存在风险，已经查看过icqq文档，两边文件格式貌似不太相同，不明白应该如何修改

**描述错误**

**复现流程**

**截图**

**版本信息**

**更多**

**Comment by Stapxs** [comment]
发自我的 iPhone在 2023年4月27日，下午4:36，FengZiLeo ***@***.***> 写道：﻿

扫码每次都会提示存在风险，已经查看过icqq文档，两边文件格式貌似不太相同，不明白应该如何修改
描述错误

复现流程

截图

版本信息

更多

**Comment by FengziLeo** [comment]
> 

问题解决。感谢。
现在新的问题是报错
[2023-04-27T19:28:07.877] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联 系。(错误码：45)
[2023-04-27T19:28:07.877] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
无论大号小号都会报错
ociq那边暂时没看到好的解决方案

**Comment by Stapxs** [comment]
这个就暂时没办法了…… 最近腾讯更新协议的速度飞快
晚点考虑把核心替换成 Icalingua ++ 维护的版本 emmm
