### ISSUE TITLE
[错误] iOS按连接没有反应

### ISSUE THREAD

**Issue by VEWION** [Stapxs/Stapxs-QQ-Lite-2.0#55]
**描述错误**
iOS按连接没有反应，没有弹出任何报错信息

**复现流程**
iOS 16.4.1(a) 在  Safari/Firefox上访问GitHub Pages DEMO网页，填写连接地址+密钥后按连接没有反应，也没有弹出任何报错信息，已反复测试Windows Edge(Chromium内核)上和Windows Electron客户端填写相同的地址+密钥后按连接秒连，在安卓13 Brave浏览器上按连接后等几秒能成功连上，但在iOS上无论等多久还是没有反应

**版本信息**
1 - 2.5.0
2 - production
3 - stapxs.github.io
4 - safari
5 - 16.4.0
6 - Mac OS
7 - undefined
8 - undefined
9 - 487 px

**Comment by Stapxs** [comment]
已知 BUG
但是我每次回去都忘了要去 Mac 上 Debug 看下报错 XD
平时手边没 Mac 没法修 ……

**Comment by VEWION** [comment]
> 已知 BUG
> 但是我每次回去都忘了要去 Mac 上 Debug 看下报错 XD
> 平时手边没 Mac 没法修 ……

希望能早日修好哈哈，实在不想用那官方QQ App了，谢谢
另外oicq2-http的icqq版本过旧我现在必须手动改成新版icqq用最新更新的协议6然后node降级到v16才能登录不然会报错误码45或者ssl相关错误（忘了记下报啥错），是不是也得在oicq2-http那边提issue，还是说后续换其他后端不用报了？

**Comment by VEWION** [comment]
![螢幕擷取畫面 2023-05-06 145852](https://user-images.githubusercontent.com/56110451/236628696-1d6d32bc-ffcb-4c87-887f-8d1d38ff1dd6.png)
使用inspect.dev看到console报这个错

**Comment by Stapxs** [comment]
> ![螢幕擷取畫面 2023-05-06 145852](https://user-images.githubusercontent.com/56110451/236628696-1d6d32bc-ffcb-4c87-887f-8d1d38ff1dd6.png)
> 
> 使用inspect.dev看到console报这个错

这几个是应用在线通知的获取报错 emmm 我 API 改了还没重写

主要是需要看看执行连接操作之后有没有报错 XD

**Comment by Stapxs** [comment]
> > 已知 BUG
> 
> > 但是我每次回去都忘了要去 Mac 上 Debug 看下报错 XD
> 
> > 平时手边没 Mac 没法修 ……
> 
> 
> 
> 希望能早日修好哈哈，实在不想用那官方QQ App了，谢谢
> 
> 另外oicq2-http的icqq版本过旧我现在必须手动改成新版icqq用最新更新的协议6然后node降级到v16才能登录不然会报错误码45或者ssl相关错误（忘了记下报啥错），是不是也得在oicq2-http那边提issue，还是说后续换其他后端不用报了？

[icqq](https://github.com/icqqjs/icqq) 是 oicq 的一个 fork 维护的版本
我是看它维护比 oicq 自己积极才换上去的 emmmm
不过我 packages.json 写死了版本可能 icqq 它更新了我没更新 XD 我晚点看看
那边不报也行我看见了就好（

**Comment by VEWION** [comment]
> > ![螢幕擷取畫面 2023-05-06 145852](https://user-images.githubusercontent.com/56110451/236628696-1d6d32bc-ffcb-4c87-887f-8d1d38ff1dd6.png)
> > 使用inspect.dev看到console报这个错
> 
> 这几个是应用在线通知的获取报错 emmm 我 API 改了还没重写
> 
> 主要是需要看看执行连接操作之后有没有报错 XD

<img width="1001" alt="Screenshot 2023-05-06 at 5 50 18 PM" src="https://user-images.githubusercontent.com/56110451/236637251-64882f7a-73e1-4dee-904e-92420c0a82ba.png">
用mac再看console反复按连接按键也只有最下面那句最左边9字那里一直涨，就是只有反复报这个错，没有其他错误，还是得等你来搞了哈哈，不懂开发只能尽量帮忙报错

**Comment by VEWION** [comment]
> > > 已知 BUG
> > 
> > 
> > > 但是我每次回去都忘了要去 Mac 上 Debug 看下报错 XD
> > 
> > 
> > > 平时手边没 Mac 没法修 ……
> > 
> > 
> > 希望能早日修好哈哈，实在不想用那官方QQ App了，谢谢
> > 另外oicq2-http的icqq版本过旧我现在必须手动改成新版icqq用最新更新的协议6然后node降级到v16才能登录不然会报错误码45或者ssl相关错误（忘了记下报啥错），是不是也得在oicq2-http那边提issue，还是说后续换其他后端不用报了？
> 
> [icqq](https://github.com/icqqjs/icqq) 是 oicq 的一个 fork 维护的版本 我是看它维护比 oicq 自己积极才换上去的 emmmm 不过我 packages.json 写死了版本可能 icqq 它更新了我没更新 XD 我晚点看看 那边不报也行我看见了就好（

嗯嗯，我看oicq2-http里的icqq是0.0.33，版本很老了，不过貌似最新版0.3.2也有其他人提issue有我说的那个ssl报错，我自己是降级到node v16暂时解决，不知道会不会有兼容性之类的问题，也许可以等icqq作者解决再直接更新oicq2-http(?)

**Comment by Stapxs** [comment]
问题已修正（cd9aa8d50ad0e57072b21b64b6686bb1d2297039）请检查功能是否正常。

**Comment by Stapxs** [comment]
CC #56，发现了另一个问题 ……

**Comment by VEWION** [comment]
已成功正常连接！感谢！但发现有一个小问题是如果第一次填写信息错误按连接报错以后就算再填正确的信息按连接还是会无报错没反应没连接，必须刷新网页再第一次就填正确信息才可以连接

**Comment by Stapxs** [comment]
嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（

**Comment by VEWION** [comment]
> 嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（

那就算了反正能用了不要紧了哈哈哈哈，那我close issue了，再次感谢修复

**Comment by Stapxs** [comment]
> 嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（

优化了重连机制 emmm 主要是发现 iOS 浏览器一置于后台就会断连，现在如果是意外断开的会尝试一次自动重连
二次连接没有反应的问题也修掉了 XD

**Comment by VEWION** [comment]
> > 嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（
> 
> 优化了重连机制 emmm 主要是发现 iOS 浏览器一置于后台就会断连，现在如果是意外断开的会尝试一次自动重连 二次连接没有反应的问题也修掉了 XD

有自动重连实在太好了！另外想请问一下iOS safari消息列表右键有望在短时间内修好吗？还是说比较难修呢？因为每次关后台再打开会重置列表必须从好友页重新点出来有一点麻烦😅谢谢

**Comment by Stapxs** [comment]
> > > 嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（
> > 
> > 
> > 优化了重连机制 emmm 主要是发现 iOS 浏览器一置于后台就会断连，现在如果是意外断开的会尝试一次自动重连 二次连接没有反应的问题也修掉了 XD
> 
> 有自动重连实在太好了！另外想请问一下iOS safari消息列表右键有望在短时间内修好吗？还是说比较难修呢？因为没有置顶的话每次关后台再打开会重置列表必须从好友页重新点出来有一点麻烦😅谢谢

现在先在电脑上设置好导出一份设置文件过去用吧 XD 我下周修 emmm 你可以开个 issue 放着防止我忘了（

**Comment by VEWION** [comment]
> > > > 嘛因为断开重连操作要重置不少数据我写的乱七八糟的不想改就摆烂了没修（
> > > 
> > > 
> > > 优化了重连机制 emmm 主要是发现 iOS 浏览器一置于后台就会断连，现在如果是意外断开的会尝试一次自动重连 二次连接没有反应的问题也修掉了 XD
> > 
> > 
> > 有自动重连实在太好了！另外想请问一下iOS safari消息列表右键有望在短时间内修好吗？还是说比较难修呢？因为没有置顶的话每次关后台再打开会重置列表必须从好友页重新点出来有一点麻烦😅谢谢
> 
> 现在先在电脑上设置好导出一份设置过去用吧 XD 我下周修 emmm 你可以开个 issue 放着防止我忘了（

完全忘了有这办法！issue现在已经有Firefox那个类似的应该不用开了(?)(不知道是不是同类问题)

**Comment by Stapxs** [comment]
[fe27c7d](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/commit/fe27c7d3bc59dac75bc4656e812a29beb1b5d4e3) 修正了消息列表右击菜单在 Safrai iOS 无效的问题
