### ISSUE TITLE
[提醒] 关于协议变更暂时无法正常登录的问题

### ISSUE THREAD

**Issue by Stapxs** [Stapxs/Stapxs-QQ-Lite-2.0#57]
icqq 已更新 —— oicq 的正在合并流程中
如果你使用了 oicq2-http，请更新仓库重新运行 `yarn` 指令更新依赖（[3b79da4](https://github.com/Tim-Paik/oicq-http2/commit/3b79da4d618a4d11d3ccdbce0be77f54c9eca329)）
如果在使用 Android Watch 登录时遇到环境异常的情况 emmm 可以暂时换用 iPad(5) 登陆方式
![图片](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/72ebedf0-bcc5-4a65-910e-945910ed1572)

-------------------

你 QQ 的协议貌似又又又更新了 …… 所以 oicq 系的全家都炸了 emmm 

经过尝试目前 oicq v2 主仓库的最新版本是可用的但是有点问题会报错 XD
\> https://github.com/takayama-lily/oicq/issues/521

icqq（oicq v2) 目前无法使用，看看会不会更新 ——
\> https://github.com/icqqjs/icqq/issues/29

oicq-icalingua-plus-plus（oicq v1）根据群友反映也没法登录了 ……
\> https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/664

总之，如果遇到了登录问题 …… 不要悲伤不要心急 —— 因为我现在也上不去了

**Comment by GeraltLee** [comment]
太蛋疼了qq，自从4月下旬开始到现在就没正常过，每隔几天就报个无法登陆

**Comment by Stapxs** [comment]
> 太蛋疼了qq，自从4月下旬开始到现在就没正常过，每隔几天就报个无法登陆

之前我是一直在用之前的 token 维持登录 …… 然后现在 token 格式一改直接完蛋（恼
只能等大佬想办法修一修了

**Comment by GeraltLee** [comment]
> > 太蛋疼了qq，自从4月下旬开始到现在就没正常过，每隔几天就报个无法登陆
> 
> 本来我是一直在用之前的 token 维持登录 …… 然后现在 token 格式一改直接完蛋（恼 只能等大佬想办法修一修了

我服务器在香港，人在美利坚，想扫码都不行。token的话这个小号从4月到现在的token是不停地变，没有一个能持久用的。。。只能坐等佬来修（悲）
