### ISSUE TITLE
[建议]修改文档

### ISSUE THREAD

**Issue by red-co** [Stapxs/Stapxs-QQ-Lite-2.0#60]
1. "platform" 改为 6,(默认配置的5无法使用)
2. 创建 .oicq/account/passowrd 文件夹，(因为这里文件夹不存在会出现  error) 

非常感谢你的工作，

**Comment by red-co** [comment]
你好呀，你问 client 的密钥是什么/怎么配置？
地址是 0.0.0.0:5700 ，密码 不知道，config  文件中没有类似的条目，

**Comment by Stapxs** [comment]
> 你好呀，你问 client 的密钥是什么/怎么配置？ 地址是 0.0.0.0:5700 ，密钥 不知道，config 文件中没有类似的条目，

密钥就是 config 里的 `access_token`
