### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by Liunkwww** [Stapxs/Stapxs-QQ-Lite-2.0#61]
**描述错误**
使用最新发布版本可连接，但点开聊天界面无输入，仅在启动时控制台有错误提示，点击聊天界面无任何错误提示。

**截图**
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/68682912/a8953e55-e3e7-45fa-a6e2-d68b1f1b05c1)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/68682912/fafbcd48-1611-4810-b3f3-15c29aeec6cf)

**版本信息**
Stapxs QQ Lite - 2.5.0 ( production )

**更多**
使用GitHub Pages构建的web版本无法连接，控制台报错如下
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/68682912/163051e9-98b8-48c3-810a-ca96fd21f1d7)
自己构建web页面失败，报错如下
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/68682912/da8c1166-a07d-4a53-904d-0eb1a8199e54)
辛苦佬惹

**Comment by Stapxs** [comment]
> 使用GitHub Pages构建的web版本无法连接，控制台报错如下

尝试完整输入 `ws://localhost:5700` 连接

**Comment by Liunkwww** [comment]
> > > 使用最新发布版本可连接，但点开聊天界面无输入，仅在启动时控制台有错误提示，点击聊天界面无任何错误提示。
> > 
> > 
> > 需要更详细的调试信息确认版本 连接 bot 之后在 `设置 - 高级 - 输出调试信息` 获取
> > > 使用GitHub Pages构建的web版本无法连接，控制台报错如下
> > 
> > 
> > 尝试完整输入 `ws://127.0.0.1:5700` 连接
> > > 自己构建web页面失败，报错如下
> > 
> > 
> > emmm 没遇到，奇怪
> 
> 2按你说的解决惹，3我猜测是我依赖的问题（x 1 - 2.5.0 2 - production 3 - . 4 - chrome 5 - 104.0.5112 6 - Windows 10 7 - oicq2 8 - 1.2.1 9 - 941 px 10 - 20.3.12 11 - C:\Users\poera

在使用自动构建的web界面时，开启全部消息通知，然后就出了和1一样的问题，不同的是这次有报错了：
error: Cannot find module './undefined.vue'
    at .*\.vue$ namespace object:14:12
