### ISSUE TITLE
更新Nodejs版本

### ISSUE THREAD

**Issue by LittleChest** [Stapxs/Stapxs-QQ-Lite-2.0#67]
### 错误来源

None

### 描述错误

我打算在闲置Android上搭建一个前后端，但是Termux只能拉取Nodejs18/19

### 复现流程

1. 在任意Android上安装Termux
2. 安装yarn
3. 安装依赖并启动服务 提示项目不支持此Nodejs版本

**Comment by Stapxs** [comment]
你可以装 `nodejs-lts`(18.16.0) 然后用它装个 yarn 来跑 emmmm 看起来是没啥问题的

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/4c047270-a2fd-48cf-8439-794552f1e687)

**Comment by Stapxs** [comment]
草
前端编译完之后是静态文件 ……
你去电脑上编译一下然后搞个 nginx 就行了其实

**Comment by Stapxs** [comment]
而且我看你 fork 了代码而且已经用 action 构建过了

你可以直接把你 fork 仓库的 pages 分支 clone 下来部署就行了

**Comment by LittleChest** [comment]
> 而且我看你 fork 了代码并且已经用 action 构建过了
> 
> 你可以直接把你 fork 仓库的 pages 分支 clone 下来部署就行了

我用Nginx部署了一下 css和js都不加载
然后想到直接用`yarn serve`部署一个算了

顺便问一下 通知功能不支持http吗 我用GitHub Pages（无https）时Chrome没有提示开启通知权限之类的

**Comment by Stapxs** [comment]
> 我用Nginx部署了一下 css和js都不加载
> 
> 然后想到直接用`yarn serve`部署一个算了

想看下网页的控制台

> 顺便问一下 通知功能不支持http吗 我用GitHub Pages（无https）时Chrome没有提示开启通知权限之类的

首次收到消息（私聊或者 at）的时候才会申请权限
如果没有的话看看有没有报错 emmmm

**Comment by LittleChest** [comment]
> 想看下网页的控制台

因为失败了所以文件全都被删掉了 下次一定（

> 首次收到消息（私聊或者 at）的时候才会申请权限 如果没有的话看看有没有报错 emmmm

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/81231195/a321e7a3-0a9d-4edf-b757-0884cd3d6359)
我用Firefox看了下 http不行
