### ISSUE TITLE
[ 提醒 ] 暂停维护通知

### ISSUE THREAD

**Issue by Stapxs** [Stapxs/Stapxs-QQ-Lite-2.0#73]
因为我现在 QQ 号用旧的登陆方式已经完全上不去了 …… 新的 sign 签名登陆方式有冻结风险
由于我自己的账号有工作需要 …… 手头又没别的账号可以用于测试

所以 ……
在有更稳定的登陆方式之前我没法进行开发测试工作（躺
进行一个摆烂

**Comment by safesaffawa** [comment]
作者方便与我沟通吗 可以的话 能不能通过qq来细聊啊UwU

**Comment by Stapxs** [comment]
> 作者方便与我沟通吗 可以的话 能不能通过qq来细聊啊UwU

1007028430

**Comment by fbewivpjsbsby** [comment]
Shamrock 可以链接，获取群组但无法获取聊天内容。

**Comment by Stapxs** [comment]
> Shamrock 可以链接，获取群组但无法获取聊天内容。

它没获取历史消息的功能 emmm 在打开的时候别人新发的消息可以显示出来吗

**Comment by fbewivpjsbsby** [comment]
> > Shamrock 可以链接，获取群组但无法获取聊天内容。
> 
> 它没获取历史消息的功能 emmm 在打开的时候别人新发的消息可以显示出来吗 如果希望适配建议开个新的 issue …… 不要在这个下面聊

原项目被 takedown。
