### ISSUE TITLE
在处理新好友请求时点击拒绝也会添加此好友

### ISSUE THREAD

**Issue by LittleChest** [Stapxs/Stapxs-QQ-Lite-2.0#74]
### 错误来源

QQ Bot

### 描述错误

在处理新好友请求时点击拒绝也会添加此人

### 复现流程

找个小号加自己
在Stapxs QQ Lite登录被添加的账号
点击列表中的系统消息
拒绝此人
左下角提示此人已被添加 Bot后端也是

### 版本信息

1 - 2.5.7
2 - production
3 - sorry but i want to hide this
4 - chrome
5 - 116.0.0
6 - Windows 10
7 - oicq2
8 - 1.2.2
9 - 1536 px

**Comment by Stapxs** [comment]
这是已知 BUG，原因是 oicq 好友操作的方法不管传同意还是不同意都会同意，没法解决。
<img width="921" alt="截屏2023-09-16 09 52 40" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/4f09d036-5cf7-4f0e-bb64-505da1d7cc1a">

**Comment by LittleChest** [comment]
更换为其它后端可以解决这个问题吗🤔

**Comment by Stapxs** [comment]
没研究过 emmm 不知道其他后端有没有这功能 XD
