### ISSUE TITLE
[Feature Request] 兼容 OpenShamrock 协议

### ISSUE THREAD

**Issue by fbewivpjsbsby** [Stapxs/Stapxs-QQ-Lite-2.0#75]
### Feature Request

兼容 [OpenShamrock](https://github.com/whitechi73/OpenShamrock) [协议](https://whitechi73.github.io/OpenShamrock)。

### Use Cases

不影响已经登录的设备。

### Potential Benefits

相比 oicq 等在更新时不容易受到协议更新的问题。

**Comment by Stapxs** [comment]
我前阵子刚打算给 Shamrock 做兼容 Shamrock 就没了也是服（恼

**Comment by Stapxs** [comment]
#76

**Comment by Stapxs** [comment]
<img width="1290" alt="image" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/55ad2e6b-50ff-4af4-b710-02516f5aee8e">

<br><br>
当前版本已经可用 …… 
不过暂时没有合并分支请自行尝试构建部署

Shamrock 的 token 需要在 header 中传递暂时未修改，
所以暂时无法连接拥有 token 的连接晚点再改（

基本的收发功能应该没啥问题了 XD
其他功能会慢慢检查修复 ——

**Comment by Stapxs** [comment]
完成基本的适配功能
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/76#issuecomment-1809649028
