### ISSUE TITLE
接收不到任何消息

### ISSUE THREAD

**Issue by MCheping8108** [Stapxs/Stapxs-QQ-Lite-2.0#78]
### 错误来源

None

### 描述错误

使用OICQ-http2，无法接收任何消息

### 截图

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/102772286/0a9bb631-3540-4b9a-9219-36569f584add)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/102772286/55b03923-e4ee-4668-9e8c-cfb814d65fa3)

### 版本信息

1 - 2.5.7
2 - production
3 - .
4 - chrome
5 - 104.0.5112
6 - Windows 10
7 - oicq2
8 - 1.2.2
9 - 1206 px
10 - 20.3.12

**Comment by Stapxs** [comment]
icqq 的控制台有正常输出消息吗 🤔

**Comment by MCheping8108** [comment]
> icqq 的控制台有正常输出消息吗 🤔

没有，而且一直卡在验证

**Comment by MCheping8108** [comment]
> > icqq 的控制台有正常输出消息吗 🤔
> 
> 没有，而且一直卡在验证

怎么说呢，这玩意我还是第一次用

**Comment by Stapxs** [comment]
那就是 icqq 没起来 emmm
这个我也暂时没法解决的说 XD

icqq 项目主页有群链接可以进去问问 emmm
不过最近 qq bot 圈子水深火热的 …… 不一定好搞
https://github.com/icqqjs/icqq

**Comment by Stapxs** [comment]
然后 wiki 里提到的 oicq-http2 可能不一定能用 emmmm
tx 大改验证方式之后我就没去试过有没有效了 XD
