### ISSUE TITLE
[错误] lagrange.onebot 消息

### ISSUE THREAD

**Issue by mole828** [Stapxs/Stapxs-QQ-Lite-2.0#79]
### 错误来源

None

### 描述错误

"getSystemMsg" "getChatHistoryFist" "getRoamingStamp" "getClassInfo" 等诸多事件出现 retcode 为 404 的情况

### 复现流程

docker 部署 image: ghcr.io/lagrangedev/lagrange.onebot:edge 采用 ForwardWebSocket
然后使用 Stapxs-QQ-Lite-2.0 进行连接报错

### 截图

<img width="936" alt="截屏2024-03-20 18 42 30" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/78151640/f96b79d8-87c1-4169-9bf2-d022ba6fa1af">
<img width="933" alt="image" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/78151640/b57f1450-6eae-4ea1-98ff-89ea1c372f4d">

### 版本信息

分支： 8ab31a4a733ea6c9b70b3d5bed1d58246e92f3e6

**Comment by Stapxs** [comment]
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/76#issuecomment-1961307789

lagrange 获取历史记录之类的功能暂时还没兼容，最近有点忙（趴

**Comment by mole828** [comment]
嗯嗯，理解理解（好快的回
那可以简单说说支持哪个版本的lagrange嘛？

**Comment by Stapxs** [comment]
目前兼容的 Lagrange 还是不太能用的样子 XD
等我有空适配完这样（x

**Comment by Stapxs** [comment]
-> d2bd2e2940a832bc456e22ada39b03e56764bf11

已完成对新增获取历史消息、获取收藏表情的支持，剩余两条：
- getSystemMsg：获取系统消息（e.g. 加群通知）
- getClassInfo：获取分组信息

Lagrange 暂未支持，不过不怎么影响用 XD
