### ISSUE TITLE
[错误] 网页端白屏

### ISSUE THREAD

**Issue by nice2cu1** [Stapxs/Stapxs-QQ-Lite-2.0#9]
**描述错误**

构建完成之后访问网页是白屏，网页资源能够正常加载，界面却是白屏。
我使用的http-server来作为http服务器

**复现流程**

**截图**

![image](https://user-images.githubusercontent.com/33564254/205605774-f5d9902f-eb6c-45bf-8034-5e18559b4018.png)

**版本信息**

http-server version: 14.1.1
nodejs verison: 18.12.1

**更多**

这是我的构建信息
https://gist.futils.com/?46bbc9eec67fcaaf#4VM7YF43dWbpwjreJZ9fPkEwhKCFMqyj1xDdF5DxULgk

**Comment by Stapxs** [comment]
构建前有修改 `config/index.js` 下的目标地址么：
![image](https://user-images.githubusercontent.com/42486439/205773677-0abda6ef-9736-4b1d-b3b6-332077aa6aee.png)
它会影响到所有静态资源最终被生成的链接
![image](https://user-images.githubusercontent.com/42486439/205774107-624cf2fa-019a-42a6-8809-363726391bfd.png)

**Comment by nice2cu1** [comment]
@Stapxs 此处我设置为了访问网页端的域名
![image](https://user-images.githubusercontent.com/33564254/205821768-77af498c-bebe-4844-8128-20a335ed3a67.png)

**Comment by Stapxs** [comment]
emmm 前几天有点忙忘记回复了 ……

关于这个应该还有一些 404 掉的资源吧 XD
我想看看那些资源的地址

不过，
最近把项目升级为了 Vue3 的版本，构建方式也有点变更（换了个包管理）
总之，更新下新的代码然后看下新的构建说明再试一下吧 XD
整个都和之前不太一样
