### ISSUE TITLE
[错误]连接llonebot有一些问题

### ISSUE THREAD

**Issue by Potatoii** [Stapxs/Stapxs-QQ-Lite-2.0#92]
### 错误来源

Stapxs QQ Lite

### 描述错误

直接下载了release中的exe测试, 开了ws端口, ws可以成功连接, 可以获取到账号信息和好友列表, 但是无法发送消息
看了ws的消息是请求了getSystemMsg和getClassInfo, 但是这两个请求后端都返回了不支持的api, 我看了下ob11的公开api中也没有这两个
(不知道是不是应该请求get_msg这类的?)

### 截图

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/3d76c209-5258-449f-aa72-287d988f8d20)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/bebb0f82-cd52-43ab-88fe-b2840cbb81ed)

### 版本信息

1 - 2.6.11
2 - production
3 - .
4 - chrome
5 - 118.0.5993
6 - Windows 10
7 - LLOneBot
8 - 3.23.0
9 - 871 px
10 - 27.3.8

### 更多

发消息时的报错:
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/768086d0-926a-42af-9e1f-dda2c9de4c23)

**Comment by Stapxs** [comment]
这俩是连接后获取系统通知、分组信息的内容 llonebot 没有实现，不影响其他功能 emmmm
可以打开全部日志输出后在日志里搜索一下 echo 为 SendMsgBack 的内容嘛（趴

<img width="501" alt="image" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/6e409519-c7b6-4ff4-94cf-6d190a827072">
<img width="1094" alt="image" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/a5af25e3-a7fa-42b2-9fb4-b5eeed090e55">

**Comment by Potatoii** [comment]
> 这俩是连接后获取系统通知、分组信息的内容 llonebot 没有实现，不影响其他功能 emmmm 可以在日志里搜索一下 echo 为 SendMsgBack 的内容嘛（趴

点击发送消息控制台输出的报错就是那个message_list报错, 截图我上面贴了, 好像没走到sendmsgback就寄了= =

**Comment by Stapxs** [comment]
我突然发现我忘记给 llonebot 写配置文件了只写了 napcat 的……会默认调拉格兰的配置文件可能会有点问题
待我进行一个写 😭

**Comment by Potatoii** [comment]
okok, 关注这个项目很长时间了, 爱信等

**Comment by Stapxs** [comment]
https://1drv.ms/u/s!AqGYne94U9-CkexkwG_Kg9RwS6gloQ?e=16Vc2B

可以先试一下（趴

**Comment by Potatoii** [comment]
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/9ab90479-88f5-4216-ab1b-98f1262c4376)
看来还是有点问题..?

**Comment by Stapxs** [comment]
这些不存在的事件理论上说应该不影响才是（趴
还是发不了消息么（

**Comment by Potatoii** [comment]
之前点发送按钮是只有控制台报错但是没反应的, 现在点发送按钮会转圈圈, 控制台报错是上面贴的图, ws的消息如下
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/d0dab38c-a7e1-412c-877e-eab8ce844ef5)

**Comment by Stapxs** [comment]
把 llonebot 配置文件的 reportSelfMessage 开出来看看（趴
自动获取发送的消息好像有点问题……

看看手机端啥的消息应该被发出去了吧

**Comment by Potatoii** [comment]
我试了一下docker起的llob和ntqq插件的llob都没有发出去消息, 所以上报自身消息确实也不会有输出吧

**Comment by Stapxs** [comment]
我部署一个试试（趴
测了 napcat 没测 llonebot（

**Comment by Potatoii** [comment]
辛苦了

**Comment by Stapxs** [comment]
![E60D003657F3D1C3782A8F8EE1A76397](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/9fb881d9-8835-49c2-bc6d-d81606274266)

高血压起来了
再试试（
https://1drv.ms/f/s!AqGYne94U9-CkexjsT2D4cwaU1BSjw?e=nCKddG

<img width="550" alt="image" src="https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/42486439/aaac56b7-4175-4821-8b9e-834cf42bed4b">

把这个打开（

**Comment by Potatoii** [comment]
可以用了! 虽然有些小问题, 但是收发消息都ok了!感谢!

**Comment by Stapxs** [comment]
有问题可以再开 issue 说（x
llonebot 确实没全面测试

**Comment by Stapxs** [comment]
https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/releases/tag/v2.7.2
