### ISSUE TITLE
[错误]Websocket 反代到子目录异常

### ISSUE THREAD

**Issue by Potatoii** [Stapxs/Stapxs-QQ-Lite-2.0#93]
### 错误来源

Stapxs QQ Lite

### 描述错误

网页端wss连接可以发出去, 但是连接握手之后就没有然后了

### 复现流程

llob的后端, 用nginx反代出来的wss, 点击连接可以成功创建websocket连接, 但是页面没有反应

### 截图

![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/49669612/dbac2ac4-adc8-40b4-af62-cf213a0fc920)

### 版本信息

2.7.2

**Comment by Stapxs** [comment]
写完整 wss:// 试试（
自动判断 SSL 写的有点问题一直都没改好

**Comment by Potatoii** [comment]
wss的判断倒是对的, 页面确实发起了wss的连接, 后端也收到了, 然后就没有下一步了..

**Comment by Stapxs** [comment]
🤔

**Comment by Stapxs** [comment]
没复现出来，可以的话可以看一下 nginx 的反代设置吗

**Comment by Potatoii** [comment]
location /ws {
    proxy_pass    http://192.168.31.253:3011;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

**Comment by Stapxs** [comment]
哦，我之前也遇到过这个问题，反代到子目录下之后连上了 ws 但是完全不交互……
不是 sql 自己的问题
暂时没搞清楚是什么问题，可以先不往子目录代

**Comment by Stapxs** [comment]
问了下作者解决了（x
参考一下，proxy_pass 加个 rewrite 把 ws 子目录重写掉就好了

~~~nginx
location ^~ /ws {
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  
  rewrite ^/ws /$1 break;
  proxy_pass http://frps:3010;
}
~~~

**Comment by Potatoii** [comment]
我超, 确实解决了, 牛!
