### ISSUE TITLE
[Bug] electron 客户端的一些问题

### ISSUE THREAD

**Issue by htxzdfunny** [Stapxs/Stapxs-QQ-Lite-2.0#98]
### 错误来源

其他

### 描述错误

RT, 主页按钮红线以上的部分是点不到的, 必须点红线以下的部分
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/bf0774cc-c20b-46be-9eac-48c4bea9695c)

### 复现流程

用鼠标仔细点点点即可

### 截图

截图在上面呐, 不过这里再补两张实际证明
通过指针的变化可以明显看出来x
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/493f5dc0-5aa4-4687-9872-6719c976f809)
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/40c509eb-d1aa-43d3-b2a3-7cf5c2bd211d)

### 版本信息

悲报: 调试信息也弹不出来
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/276a6a03-c76b-48a8-904e-0349766ec0e9)

用的客户端版本是从 release 下的 [v2.7.9](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/releases/tag/v2.7.9) , 系统是 `Windows 10 21H2 19044.3086`

### 更多

```JavaScript
registerServiceWorker.ts:37 注册 service worker 时发生错误:  TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('app://.') is not supported.
    at e (index.js:75:6)
    at index.js:57:9
```

**Comment by Stapxs** [comment]
其实是标题栏区域，标题栏被隐藏掉了但是保留了拖动区域导致覆盖掉了一小部分地方
暂时不知道怎么解决好 emmmm
后续可以考虑修一下 🤔

**Comment by Stapxs** [comment]
调试信息是个已知 bug（趴
没连接 bot 的时候获取 bot 信息忘记判断了 😣

话说你这个左栏的亚克力模糊看起来没有耶
如果没有的话那就也是 BUG 了（瘫

**Comment by Stapxs** [comment]
以及你这个左栏的亚克力模糊是不是没有看起来 🤔
那应该是有问题的（瘫

**Comment by htxzdfunny** [comment]
> 调试信息是个已知 bug（趴 没连接 bot 的时候获取 bot 信息忘记判断了 😣
> 
> 话说你这个左栏的亚克力模糊看起来没有耶 如果没有的话那就也是 BUG 了（瘫

原来是有亚克力模糊的吗
我还以为设计就是半透明的 看字挺费力的 (
![image](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/assets/54425771/a32f8f35-ae98-463b-bbca-e8e16dce1a36)

**Comment by Stapxs** [comment]
是有的啦（趴
我测试的环境是 win11 所以不太清楚 10 怎么样 emmm
晚点我一起看看好了

**Comment by Stapxs** [comment]
46a3c372f5527199954074f7161bbff335e68512
